version: '3'
services:
  express-app:
    build: .
    ports:
      - "${PORT}:3000"
    depends_on:
      - mariadb
    environment:
      DB_HOST: ${DB_HOST}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - .:/app
    command: sh -c 'if [ "$$NODE_ENV" = "development" ]; then npm run dev; else npm start; fi'
    networks:
      - mariadb-express-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - mariadb-express-network
      - mariadb-phpmyadmin-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
    ports:
      - "${MYADMIN_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - mariadb-phpmyadmin-network

networks:
  mariadb-express-network:
    driver: bridge
  mariadb-phpmyadmin-network:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
