FROM node:latest as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:alpine
WORKDIR /app
COPY --from=build-stage /app/dist ./build
COPY package*.json ./
RUN npm install --only=production
EXPOSE 3000
CMD ["node", "build/app.js"]
